name: 🎉 iOS Build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: swift-DEVELOPMENT-SNAPSHOT-2021-11-12-a

    - name: Checkout
      uses: actions/checkout@v2


    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Install dependencies
      run: |
          flutter pub get
          pod install
      working-directory: ios

    - name: Build iOS app
      run: flutter build ios --release --no-codesign

    - name: Prepare Payload
      run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
      working-directory: build/ios/iphoneos

    - name: Zip output
      run: zip -qq -r -9 FlutterIpaExport.ipa Payload
      working-directory: build/ios/iphoneos

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/ios/iphoneos/FlutterIpaExport.ipa
        tag: v1.0
        overwrite: true
        body: "This is the first release"
